# SPDX-FileCopyrightText: Copyright (c) 2025 Cisco and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

name: agent-bridge

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
