name: Run Tests

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  TYK_VERSION: v5.8.0-alpha8
  TARGET_OS: linux

jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: make setup
      - uses: actions/setup-go@v5
        with:
          go-version-file: "plugins/go.mod"
          cache-dependency-path: |
            plugins/go.sum
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          args: --timeout=10m plugins/

  unittest:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "plugins/go.mod"
          cache-dependency-path: |
            plugins/go.sum

      - name: Cache Tyk, Search Library and model
        id: cache-tyk-search-library-model
        uses: actions/cache@v4
        with:
          path: ./tyk-release-${{ env.TYK_VERSION }}
          key: ${{ runner.os }}-${{ env.TYK_VERSION }}

      - run: |
          make TYK_VERSION="${{ env.TYK_VERSION }}" setup
          mkdir -p tyk-release-${{ env.TYK_VERSION }}/models/
          make TYK_VERSION="${{ env.TYK_VERSION }}" download_models_for_semrouter

      - name: Run tests
        run: |
          make TYK_VERSION="${{ env.TYK_VERSION }}" test
